name: PortNLP - NLP Lab at Portland State
url: 'http://127.0.0.1:4000/'

# Base pathname for links.
base: ''

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# # Sections on the "people" page.
# roles:
#   - key: faculty
#     name: Faculty
#   # - key: postdoc
#   #   name: Researchers
#   # - key: phd
#   #   name: PhD Students
#   - key: current
#     name: Current Students
#   - key: past
#     name: Past Students

# Number of news stories on the front page.
front_page_news: 8

# make pages for the _projects folder
collections:
  projects:
    output: false

  nlpblogs:
    output: false

# Navigation bar links.
navigation:
  # - title: Home
  #   link: /
  # - title: Group
  #   link: /#group
  # - title: Repo
  #   link: /publications.html
  # # - title: Events
  # #   link: /events.html
  # - title: Github
  #   link: /github.html
  # - title: Insights
  #   link: /insights.html
  # - title: Gallery
  #   link: /gallery.html